# Generated by Django 5.1.4 on 2024-12-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва видавця')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='publishers_logos/', verbose_name='Логотип видавця')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва гри')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='board_games_images/', verbose_name='Картинка гри')),
                ('category', models.CharField(choices=[('Стратегії', 'Стратегії'), ('Економіка', 'Економіка'), ('Військові', 'Військові'), ('Америтреш', 'Америтреш'), ('Євро', 'Євро'), ('Абстракти', 'Абстракти'), ('Пригоди', 'Пригоди'), ('Кооперативні', 'Кооперативні'), ('Один проти всіх', 'Один проти всіх'), ('На удачу', 'На удачу'), ('На кубиках', 'На кубиках'), ('На спритність', 'На спритність'), ('Логічні', 'Логічні'), ('Вікторина', 'Вікторина'), ('Мафія', 'Мафія'), ('Містобудівні', 'Містобудівні'), ('Творчі', 'Творчі'), ('На асоціації', 'На асоціації'), ('Розмовні', 'Розмовні'), ('Класика', 'Класика'), ('Квести', 'Квести'), ('Історія', 'Історія'), ('Фантастика', 'Фантастика'), ('Фентезі', 'Фентезі'), ('Жахалки', 'Жахалки'), ('Міти Ктулху', 'Міти Ктулху'), ('Зомбі', 'Зомбі'), ('Постапокаліпсис', 'Постапокаліпсис'), ('Цивілізація', 'Цивілізація'), ('Гумор', 'Гумор'), ('Головоломки', 'Головоломки'), ('Спорт', 'Спорт'), ('Гонки', 'Гонки'), ('Колекційні карткові ігри', 'Колекційні карткові ігри'), ('Magic The Gathering', 'Magic The Gathering')], max_length=50, verbose_name='Категорія')),
                ('age', models.CharField(choices=[('2-3 роки', '2-3 роки'), ('4-5 років', '4-5 років'), ('6-7 років', '6-7 років'), ('8-9 років', '8-9 років'), ('10-13 років', '10-13 років'), ('14+ років', '14+ років')], max_length=20, verbose_name='Вік')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_games', to='main.publisher', verbose_name='Видавець')),
            ],
        ),
    ]
